### ISSUE TITLE
After upgrade nothing is loading properly

### ISSUE THREAD

**Issue by sant-sh** [YunoHost-Apps/yourls_ynh#11]
Today I have updated the lates available upgrade and after that neither admin page is loading nor I am able to shortenn the URL.

![image](https://user-images.githubusercontent.com/9120889/102020883-1b7b6500-3da2-11eb-9859-fa5ce2e02cce.png)

**Comment by anmol26s** [comment]
Well Helloo
It looks like we will need to fix few things then. ;)
1. Can you show the nginx config file? Replace YOUR_DOMAIN with domain name in below command.

`$ cat /etc/nginx/conf.d/YOUR_DOMAIN.d/yourls.conf`

2. Can you access the broken admin interface publicly ?

**Comment by sant-sh** [comment]
Sure, I am happy to help :)

1. Here is the nginx config
```
#sub_path_only rewrite ^/$ / permanent;
location / {

  alias /var/www/yourls/;

  # Force usage of https
  if ($scheme = http) {
    rewrite ^ https://$server_name$request_uri? permanent;
  }

  try_files $uri $uri/ /var/www/yourls/yourls-loader.php;


  index index.php index.html index.htm;

  location ~ [^/]\.php(/|$) {
     fastcgi_split_path_info ^(.+?\.php)(/.*)$;
     fastcgi_pass unix:/var/run/php7.3-fpm-yourls.sock;
     fastcgi_index index.php;
     include fastcgi_params;
     fastcgi_param REMOTE_USER     $remote_user;
     fastcgi_param PATH_INFO       $fastcgi_path_info;
     fastcgi_param SCRIPT_FILENAME $request_filename;
    }

  # Include SSOWAT user panel.
  include conf.d/yunohost_panel.conf.inc;
}
```


2. Can you access the broken admin interface publicly ?
Nope. 
Here is what i am getting without SSO cache. 
![image](https://user-images.githubusercontent.com/9120889/102056966-3639f200-3e13-11eb-999e-8dafd38e624e.png)
After clicking admin it will go for SSO redirect and then after providing the credentials I will be presented with broken page

**Comment by anmol26s** [comment]
Yes there is a php bug in the source.
Did a quick fix. Lets see if it bring back things.

Can you upgrade with below command and see if this fixes it?
`# yunohost app upgrade -u https://github.com/YunoHost-Apps/yourls_ynh/tree/admin_fix yourls --debug `

**Comment by sant-sh** [comment]
Yes, it worked.

Thanks for the quick fix.
