### ISSUE TITLE
Shorten links don't work

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/yourls_ynh#3]
Hi

I tried to create a short link with yourls on a VM.
The interface seems to work, my link was created, but when I use the link, I have an error, saying : "File not found."

Same thing with the 3 other links already registered in yourls after installation.

**Comment by anmol26s** [comment]
This should me fix now. 
Thanks for using this package.

**Comment by maniackcrudelis** [comment]
Actually I was just trying it to find a way to reduce the public address of our kanboard.
But, this app works well (now) and seems to be light.
So I'm going to adopt it for myself :)

**Comment by anmol26s** [comment]
> Actually I was just trying it to find a way to reduce the public address of our kanboard.

I will try to implement LDAP and fail2ban support support for yourls.

**Comment by maniackcrudelis** [comment]
Wonderful :)
As I understand, for now,  you can only add a new link if you have the admin password ? That's it ?

**Comment by anmol26s** [comment]
` As I understand, for now, you can only add a new link if you have the admin password ? That's it ?`
Yes
Yourls have fail2ban plugin which I will use if I fail to do what I have thought.
 A better solution is to have ldap support with SSO restricted to yunohost user for the adim page of yourls.This way yourls will be public and the admin page will be behind SSO giving it fail2ban and admin page to single(or many as set in _Yunohost app access_) user.

But I don't know how to restrict a single page(yourls admin page) to a particular user only and keeping rest of the app public.

**Comment by anmol26s** [comment]
There is public install that can make the app without admin. That mean all people can use the admin interface. But I think its not good for yourls because all internet users will have access to all the short links and would able to delete and edit it which would take away the privacy.

**Comment by maniackcrudelis** [comment]
Ok, so yourls is single user, but there's plugins to allow multi-users and ldap authentication, as well as fail2ban.
Looks like an interesting idea to work on that part.

**Comment by girowue** [comment]
Hi! 

I have the same error with fresh install. When I click any of the default short links (admin panel works OK) -> "File not found"

What is happening? How can I fix it?

Thanks.
