### ISSUE TITLE
Add php7.0-gmp and php7.0-bcmath dependencies 

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/yourls_ynh#6]
I just tried this interesting app - Thanks for this App

installation was no problem
but the shortend links do NOT work – just gives me a blank page - HTTP ERROR 500 
any idea ?

**Comment by anmol26s** [comment]
Is the admin link working ?
You will have to open link with 500 error again and show me the error: 
`$ tail -n 100 /var/logs/nginx/domain.tld.error`

**Comment by rocky-III** [comment]
Hi anmol
the yourls Admi page shows up - YES

`$ tail -n 100 /var/logs/nginx/domain.tld.error` did not work  - error `tail: cannot open`

but I looked it up in the webinterface at 

`/var/log/nginx/domain.tld-error.log`

there i found this:



`#0 /var/www/yourls/includes/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php(132): MaxMind\Db\Reader\Decoder->decodeBigUint('Y\t\x02\xAE', 4)
#1 /var/www/yourls/includes/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php(98): MaxMind\Db\Reader\Decoder->decodeByType('uint64', 2724558, 4)
#2 /var/www/yourls/includes/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php(194): MaxMind\Db\Reader\Decoder->decode(2724558)
#3 /var/www/yourls/includes/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php(105): MaxMind\Db\Reader\Decoder->decodeMap(9, 2724556)
#4 /var/www/yourls/includes/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php(98): MaxMind\Db\Reader\Decoder->decodeByType('map', 2724485, 9)
#5 /var/www/yourls/includes/vendor/maxmind-db/reader/s" while reading response header from upstream, client: 2.244.148.172, server: domain.tld, request: "GET /fg HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm-yourls.sock:", host: "domain.tld", referrer: "https://domain.tld/admin/"
2019/01/21 14:28:00 [error] 7122#7122: *5166 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: The gmp or bcmath extension must be installed to read this database. in /var/www/yourls/includes/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php:259
Stack trace:
#0 /var/www/yourls/includes/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php(132): MaxMind\Db\Reader\Decoder->decodeBigUint('Y\t\x02\xAE', 4)
#1 /var/www/yourls/includes/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php(98): MaxMind\Db\Reader\Decoder->decodeByType('uint64', 2724558, 4)
#2 /var/www/yourls/includes/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php(194): MaxMind\Db\Reader\Decoder->decode(2724558)
#3 /var/www/yourls/includes/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php(105): MaxMind\Db\Reader\Decoder->decodeMap(9, 2724556)
#4 /var/www/yourls/includes/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php(98): MaxMind\Db\Reader\Decoder->decodeByType('map', 2724485, 9)
#5 /var/www/yourls/includes/vendor/maxmind-db/reader/s" while reading response header from upstream, client: 2.244.148.172, server: domain.tld, request: "GET /dead HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm-yourls.sock:", host: "domain.tld", referrer: "https://domain.tld/admin/"`

does this explain something?

**Comment by anmol26s** [comment]
Yes 
It shows it.

Install the packages.

`$ apt-get install php7.0-gmp php7.0-bcmath`

And if it still don't work show me log again.

**Comment by rocky-III** [comment]
You are my hero... 

links are working now... 
was an update to php 7 needed? 
Anyway THANKS so much  - i really like this link shorting app now... very cooool

**Comment by anmol26s** [comment]
Thanks for reporting the issue. On my server these dependencies are pre installed by any other apps, so it works.
But these dependencies are need to be added into the app package. 
I will keep the issue open till I add them.

Thanks once again for testing and reporting.

**Comment by anmol26s** [comment]
Fixed in https://github.com/YunoHost-Apps/yourls_ynh/commit/2c387e657cb78317003740ae23b20a12982cd513 , so closing this.
